spring:
  h2:
    console:
      enabled: false
      path: /h2
  #  datasource:
  #    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
  #    username: sa
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: pring
    password: pring
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: com.asterlsker.housepit.rdbms.config.JpaNamingStrategy
    properties:
      hibernate:
        show-sql: true
        default_batch_fetch_size: 100
    open-in-view: false
---
spring.config.activate.on-profile: local
spring:
  h2:
    console:
      enabled: true
#  defer-datasource-initialization: true
#  sql:
#    init:
#      data-locations: classpath:sql/**
---
spring.config.activate.on-profile: dev
